# Command Stage Template
# Executes custom AI commands from @ai mentions in comments
#
# Supports both standalone and submodule modes:
# - Standalone: scripts in ./scripts/, systems in ./systems/
# - Submodule: scripts in ./template/scripts/, systems in ./systems/ + ./template/systems/

parameters:
  - name: workItemId
    type: string
  - name: command
    type: string
  - name: dockerImage
    type: string
    default: 'ghcr.io/opencode-ai/opencode:latest'

jobs:
  - job: ExecuteCommand
    displayName: 'Execute AI Command'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self
        displayName: 'Checkout repository'
        submodules: true

      - script: |
          # Auto-detect org from System.CollectionUri
          export AZURE_DEVOPS_ORG=$(echo "$SYSTEM_COLLECTIONURI" | sed 's|https://dev.azure.com/||' | sed 's|/$||')
          echo "##vso[task.setvariable variable=AZURE_DEVOPS_ORG]$AZURE_DEVOPS_ORG"

          # Detect submodule mode
          if [ -d "template/scripts" ]; then
            SCRIPTS="template/scripts"
            SUBMODULE_MODE="true"
            echo "Running in submodule mode"
          else
            SCRIPTS="scripts"
            SUBMODULE_MODE="false"
            echo "Running in standalone mode"
          fi
          chmod +x $SCRIPTS/*.sh scripts/*.sh 2>/dev/null || true
          echo "##vso[task.setvariable variable=SCRIPTS_DIR]$SCRIPTS"
          echo "##vso[task.setvariable variable=SUBMODULE_MODE]$SUBMODULE_MODE"
        displayName: 'Detect environment'
        env:
          SYSTEM_COLLECTIONURI: $(System.CollectionUri)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          # Fetch work item context and download attachments
          mkdir -p attachments
          ./$SCRIPTS/get-workitem-context.sh \
            --work-item-id "${{ parameters.workItemId }}" \
            --output "workitem-context.json" \
            --attachments-dir "attachments"

          # List downloaded attachments
          echo "Attachments downloaded:"
          ls -la attachments/ 2>/dev/null || echo "  (none)"
        displayName: 'Fetch work item context and attachments'
        env:
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)
          AZURE_DEVOPS_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_PAT: $(System.AccessToken)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          SUBMODULE_MODE="$(SUBMODULE_MODE)"

          # Build systems-dir arguments based on mode
          if [ "$SUBMODULE_MODE" = "true" ]; then
            SYSTEM=$(./$SCRIPTS/resolve-system-config.sh \
              --context-file workitem-context.json \
              --systems-dir systems \
              --systems-dir template/systems)
          else
            SYSTEM=$(./$SCRIPTS/resolve-system-config.sh \
              --context-file workitem-context.json)
          fi
          echo "Detected system: $SYSTEM"
          echo "##vso[task.setvariable variable=DETECTED_SYSTEM]$SYSTEM"

          # Copy OpenCode config to workspace root
          # Priority: local systems > template systems
          if [ -f "systems/_default/opencode.json" ]; then
            cp systems/_default/opencode.json ./opencode.json
            echo "Using local opencode.json"
          elif [ -f "template/systems/_default/opencode.json" ]; then
            cp template/systems/_default/opencode.json ./opencode.json
            echo "Using template opencode.json"
          fi

          # Load skills in layers
          rm -rf .opencode/skills
          mkdir -p .opencode/skills

          if [ "$SUBMODULE_MODE" = "true" ]; then
            # 1. Template default skills (generic base)
            if [ -d "template/systems/_default/skills" ]; then
              echo "Loading template default skills..."
              cp -r template/systems/_default/skills/* .opencode/skills/ 2>/dev/null || true
            fi

            # 2. Local default skills (organization-specific, can override template)
            if [ -d "systems/_default/skills" ]; then
              echo "Loading organization-specific skills..."
              cp -r systems/_default/skills/* .opencode/skills/ 2>/dev/null || true
            fi

            # 3. System-specific skills from both locations
            for systems_dir in template/systems systems; do
              if [ -d "$systems_dir/$SYSTEM/skills" ] && [ "$(ls -A $systems_dir/$SYSTEM/skills 2>/dev/null)" ]; then
                echo "Loading skills from $systems_dir/$SYSTEM..."
                cp -r $systems_dir/$SYSTEM/skills/* .opencode/skills/ 2>/dev/null || true
              fi
            done
          else
            # Standalone mode: simple loading
            if [ -d "systems/_default/skills" ]; then
              echo "Loading default skills..."
              cp -r systems/_default/skills/* .opencode/skills/ 2>/dev/null || true
            fi
            if [ -d "systems/$SYSTEM/skills" ] && [ "$(ls -A systems/$SYSTEM/skills 2>/dev/null)" ]; then
              echo "Loading skills from system: $SYSTEM"
              cp -r systems/$SYSTEM/skills/* .opencode/skills/ 2>/dev/null || true
            fi
          fi

          echo "Loaded skills:"
          ls .opencode/skills/ 2>/dev/null || echo "  (none)"

          # Load agents in layers (same pattern as skills)
          rm -rf .opencode/agents
          mkdir -p .opencode/agents

          if [ "$SUBMODULE_MODE" = "true" ]; then
            # 1. Template default agents
            if [ -d "template/systems/_default/agents" ]; then
              echo "Loading template default agents..."
              cp -r template/systems/_default/agents/* .opencode/agents/ 2>/dev/null || true
            fi

            # 2. Local default agents (can override template)
            if [ -d "systems/_default/agents" ]; then
              echo "Loading organization-specific agents..."
              cp -r systems/_default/agents/* .opencode/agents/ 2>/dev/null || true
            fi

            # 3. System-specific agents from both locations
            for systems_dir in template/systems systems; do
              if [ -d "$systems_dir/$SYSTEM/agents" ] && [ "$(ls -A $systems_dir/$SYSTEM/agents 2>/dev/null)" ]; then
                echo "Loading agents from $systems_dir/$SYSTEM..."
                cp -r $systems_dir/$SYSTEM/agents/* .opencode/agents/ 2>/dev/null || true
              fi
            done
          else
            # Standalone mode
            if [ -d "systems/_default/agents" ]; then
              echo "Loading default agents..."
              cp -r systems/_default/agents/* .opencode/agents/ 2>/dev/null || true
            fi
            if [ -d "systems/$SYSTEM/agents" ] && [ "$(ls -A systems/$SYSTEM/agents 2>/dev/null)" ]; then
              echo "Loading agents from system: $SYSTEM"
              cp -r systems/$SYSTEM/agents/* .opencode/agents/ 2>/dev/null || true
            fi
          fi

          echo "Loaded agents:"
          ls .opencode/agents/ 2>/dev/null || echo "  (none)"
        displayName: 'Resolve system configuration'

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          SUBMODULE_MODE="$(SUBMODULE_MODE)"
          SYSTEM="$(DETECTED_SYSTEM)"
          COMMAND="${{ parameters.command }}"

          # Build prompt with appropriate systems-dir arguments
          if [ "$SUBMODULE_MODE" = "true" ]; then
            PROMPT=$(./$SCRIPTS/build-prompt.sh \
              --mode command \
              --system "$SYSTEM" \
              --context workitem-context.json \
              --command "$COMMAND" \
              --systems-dir systems \
              --systems-dir template/systems)
          else
            PROMPT=$(./$SCRIPTS/build-prompt.sh \
              --mode command \
              --system "$SYSTEM" \
              --context workitem-context.json \
              --command "$COMMAND")
          fi

          # Capture agent and skills info for logging
          AGENT_NAME="command"
          SKILLS_LIST=$(ls -1 .opencode/skills/ 2>/dev/null | sed 's/\.md$//' | tr '\n' ', ' | sed 's/,$//')
          AGENTS_LIST=$(ls -1 .opencode/agents/ 2>/dev/null | sed 's/\.md$//' | tr '\n' ', ' | sed 's/,$//')

          # Log what we're sending to OpenCode
          echo "=============================================="
          echo "OPENCODE INPUT - COMMAND MODE"
          echo "=============================================="
          echo "Agent: $AGENT_NAME"
          echo "System: $SYSTEM"
          echo "Submodule Mode: $SUBMODULE_MODE"
          echo ""
          echo "--- AVAILABLE SKILLS ---"
          echo "$SKILLS_LIST"
          echo ""
          echo "--- AVAILABLE AGENTS ---"
          echo "$AGENTS_LIST"
          echo ""
          echo "--- COMMAND ---"
          echo "$COMMAND"
          echo ""
          echo "--- PROMPT ---"
          echo "$PROMPT"
          echo ""
          echo "--- OPENCODE CONFIG ---"
          cat ./opencode.json
          echo ""
          echo "=============================================="

          # Create OpenCode auth directory and inject auth.json
          mkdir -p $HOME/.local/share/opencode
          echo "$OPENCODE_AUTH_JSON" > $HOME/.local/share/opencode/auth.json

          # Build docker arguments
          DOCKER_ARGS="--rm"
          DOCKER_ARGS="$DOCKER_ARGS -e ADO_MCP_AUTH_TOKEN"
          DOCKER_ARGS="$DOCKER_ARGS -e AZURE_DEVOPS_ORG_URL=https://dev.azure.com/$AZURE_DEVOPS_ORG"
          DOCKER_ARGS="$DOCKER_ARGS -e AZURE_DEVOPS_ORG=$AZURE_DEVOPS_ORG"
          DOCKER_ARGS="$DOCKER_ARGS -e AZURE_DEVOPS_PROJECT=$SYSTEM_TEAMPROJECT"
          DOCKER_ARGS="$DOCKER_ARGS -e AZURE_DEVOPS_PAT=$ADO_MCP_AUTH_TOKEN"
          DOCKER_ARGS="$DOCKER_ARGS -e WORK_ITEM_ID=${{ parameters.workItemId }}"
          DOCKER_ARGS="$DOCKER_ARGS -v $HOME/.local/share/opencode:/root/.local/share/opencode"
          DOCKER_ARGS="$DOCKER_ARGS -v $(pwd):/workspace"
          DOCKER_ARGS="$DOCKER_ARGS -w /workspace"

          # Add CA certificates if available (for internal HTTPS endpoints)
          # Organizations can provide certs/*.crt files for internal SSL/TLS
          # Mount to /tmp/org-certs and copy to proper location in entrypoint
          CA_MOUNT=""
          if [ -d "certs" ] && ls certs/*.crt 1>/dev/null 2>&1; then
            echo "Mounting organization CA certificates..."
            CA_MOUNT="-v $(pwd)/certs:/tmp/org-certs:ro"
          fi

          # Run OpenCode with command agent
          # If CA certs mounted, copy to proper location and run update-ca-certificates
          # Must use --entrypoint to override container's default entrypoint
          # Set NODE_EXTRA_CA_CERTS so Node.js also trusts the certs
          # Use $1 for prompt (underscore is placeholder for $0)
          if [ -n "$CA_MOUNT" ]; then
            docker run $DOCKER_ARGS $CA_MOUNT --entrypoint sh \
              ${{ parameters.dockerImage }} -c '
                cp /tmp/org-certs/*.crt /usr/local/share/ca-certificates/ 2>/dev/null
                update-ca-certificates 2>/dev/null
                export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
                opencode run --agent command "$1"
              ' _ "$PROMPT" > command-result.md
          else
            docker run $DOCKER_ARGS \
              ${{ parameters.dockerImage }} run --agent command "$PROMPT" > command-result.md
          fi
        displayName: 'Execute AI Command'
        env:
          OPENCODE_AUTH_JSON: $(OPENCODE_AUTH_JSON)
          ADO_MCP_AUTH_TOKEN: $(System.AccessToken)
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          # Post response as work item comment
          RESULT=$(cat command-result.md)

          # Add agent signature to footer
          RESULT_WITH_FOOTER="${RESULT}

          ---
          *Agent: command*"

          ./$SCRIPTS/update-workitem.sh \
            --work-item-id "${{ parameters.workItemId }}" \
            --add-comment "$RESULT_WITH_FOOTER" \
            --remove-tag "ai-working"
        displayName: 'Post response to work item'
        env:
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)
          AZURE_DEVOPS_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_PAT: $(System.AccessToken)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          # Notify on failure
          if [ "$AGENT_JOBSTATUS" == "Failed" ]; then
            ./$SCRIPTS/send-teams-notification.sh \
              --type "error" \
              --work-item-id "${{ parameters.workItemId }}" \
              --message "AI command execution failed" \
              --pipeline-url "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"

            ./$SCRIPTS/update-workitem.sh \
              --work-item-id "${{ parameters.workItemId }}" \
              --add-tag "ai-failed" \
              --remove-tag "ai-working" \
              --add-comment "## AI Command Failed

          The AI command could not be executed. Check the pipeline logs for details.

          [Pipeline Logs]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId))"
          fi
        displayName: 'Handle failure'
        condition: failed()
        env:
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)
          AZURE_DEVOPS_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_PAT: $(System.AccessToken)
          TEAMS_WEBHOOK_URL: $(TEAMS_WEBHOOK_URL)
