# Implement Stage Template
# Creates feature branch, implements solution, creates PR
#
# Supports both standalone and submodule modes:
# - Standalone: scripts in ./scripts/, systems in ./systems/
# - Submodule: scripts in ./template/scripts/, systems in ./systems/ + ./template/systems/

parameters:
  - name: workItemId
    type: string
  - name: targetRepo
    type: string
    default: ''
  - name: dodConfig
    type: string
    default: 'default'
  - name: dockerImage
    type: string
    default: 'ghcr.io/opencode-ai/opencode:latest'

jobs:
  - job: ImplementSolution
    displayName: 'Implement Solution'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self
        displayName: 'Checkout repository'
        persistCredentials: true
        submodules: true

      - script: |
          # Auto-detect org from System.CollectionUri
          export AZURE_DEVOPS_ORG=$(echo "$SYSTEM_COLLECTIONURI" | sed 's|https://dev.azure.com/||' | sed 's|/$||')
          echo "##vso[task.setvariable variable=AZURE_DEVOPS_ORG]$AZURE_DEVOPS_ORG"

          # Detect submodule mode
          if [ -d "template/scripts" ]; then
            SCRIPTS="template/scripts"
            SUBMODULE_MODE="true"
            echo "Running in submodule mode"
          else
            SCRIPTS="scripts"
            SUBMODULE_MODE="false"
            echo "Running in standalone mode"
          fi
          chmod +x $SCRIPTS/*.sh scripts/*.sh 2>/dev/null || true
          echo "##vso[task.setvariable variable=SCRIPTS_DIR]$SCRIPTS"
          echo "##vso[task.setvariable variable=SUBMODULE_MODE]$SUBMODULE_MODE"
        displayName: 'Detect environment'
        env:
          SYSTEM_COLLECTIONURI: $(System.CollectionUri)

      # ai-working tag already added in Process stage

      - script: |
          # Configure git
          git config user.name "AI Agent"
          git config user.email "ai-agent@pipeline.local"

          # Create feature branch
          BRANCH_NAME="ai/${{ parameters.workItemId }}"
          git checkout -b "$BRANCH_NAME"
          echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
        displayName: 'Create feature branch'

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          # Fetch work item context and download attachments
          mkdir -p attachments
          ./$SCRIPTS/get-workitem-context.sh \
            --work-item-id "${{ parameters.workItemId }}" \
            --output "workitem-context.json" \
            --attachments-dir "attachments"

          # List downloaded attachments
          echo "Attachments downloaded:"
          ls -la attachments/ 2>/dev/null || echo "  (none)"
        displayName: 'Fetch work item context and attachments'
        env:
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)
          AZURE_DEVOPS_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_PAT: $(System.AccessToken)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          SUBMODULE_MODE="$(SUBMODULE_MODE)"

          # Build systems-dir arguments based on mode
          if [ "$SUBMODULE_MODE" = "true" ]; then
            SYSTEM=$(./$SCRIPTS/resolve-system-config.sh \
              --context-file workitem-context.json \
              --systems-dir systems \
              --systems-dir template/systems)
          else
            SYSTEM=$(./$SCRIPTS/resolve-system-config.sh \
              --context-file workitem-context.json)
          fi
          echo "Detected system: $SYSTEM"
          echo "##vso[task.setvariable variable=DETECTED_SYSTEM]$SYSTEM"

          # Copy OpenCode config to workspace root
          # Priority: local systems > template systems
          if [ -f "systems/_default/opencode.json" ]; then
            cp systems/_default/opencode.json ./opencode.json
            echo "Using local opencode.json"
          elif [ -f "template/systems/_default/opencode.json" ]; then
            cp template/systems/_default/opencode.json ./opencode.json
            echo "Using template opencode.json"
          fi

          # Load skills in layers
          rm -rf .opencode/skills
          mkdir -p .opencode/skills

          if [ "$SUBMODULE_MODE" = "true" ]; then
            # 1. Template default skills (generic base)
            if [ -d "template/systems/_default/skills" ]; then
              echo "Loading template default skills..."
              cp -r template/systems/_default/skills/* .opencode/skills/ 2>/dev/null || true
            fi

            # 2. Local default skills (organization-specific, can override template)
            if [ -d "systems/_default/skills" ]; then
              echo "Loading organization-specific skills..."
              cp -r systems/_default/skills/* .opencode/skills/ 2>/dev/null || true
            fi

            # 3. System-specific skills from both locations
            for systems_dir in template/systems systems; do
              if [ -d "$systems_dir/$SYSTEM/skills" ] && [ "$(ls -A $systems_dir/$SYSTEM/skills 2>/dev/null)" ]; then
                echo "Loading skills from $systems_dir/$SYSTEM..."
                cp -r $systems_dir/$SYSTEM/skills/* .opencode/skills/ 2>/dev/null || true
              fi
            done
          else
            # Standalone mode: simple loading
            if [ -d "systems/_default/skills" ]; then
              echo "Loading default skills..."
              cp -r systems/_default/skills/* .opencode/skills/ 2>/dev/null || true
            fi
            if [ -d "systems/$SYSTEM/skills" ] && [ "$(ls -A systems/$SYSTEM/skills 2>/dev/null)" ]; then
              echo "Loading skills from system: $SYSTEM"
              cp -r systems/$SYSTEM/skills/* .opencode/skills/ 2>/dev/null || true
            fi
          fi

          echo "Loaded skills:"
          ls .opencode/skills/ 2>/dev/null || echo "  (none)"

          # Load agents in layers (same pattern as skills)
          rm -rf .opencode/agents
          mkdir -p .opencode/agents

          if [ "$SUBMODULE_MODE" = "true" ]; then
            # 1. Template default agents
            if [ -d "template/systems/_default/agents" ]; then
              echo "Loading template default agents..."
              cp -r template/systems/_default/agents/* .opencode/agents/ 2>/dev/null || true
            fi

            # 2. Local default agents (can override template)
            if [ -d "systems/_default/agents" ]; then
              echo "Loading organization-specific agents..."
              cp -r systems/_default/agents/* .opencode/agents/ 2>/dev/null || true
            fi

            # 3. System-specific agents from both locations
            for systems_dir in template/systems systems; do
              if [ -d "$systems_dir/$SYSTEM/agents" ] && [ "$(ls -A $systems_dir/$SYSTEM/agents 2>/dev/null)" ]; then
                echo "Loading agents from $systems_dir/$SYSTEM..."
                cp -r $systems_dir/$SYSTEM/agents/* .opencode/agents/ 2>/dev/null || true
              fi
            done
          else
            # Standalone mode
            if [ -d "systems/_default/agents" ]; then
              echo "Loading default agents..."
              cp -r systems/_default/agents/* .opencode/agents/ 2>/dev/null || true
            fi
            if [ -d "systems/$SYSTEM/agents" ] && [ "$(ls -A systems/$SYSTEM/agents 2>/dev/null)" ]; then
              echo "Loading agents from system: $SYSTEM"
              cp -r systems/$SYSTEM/agents/* .opencode/agents/ 2>/dev/null || true
            fi
          fi

          echo "Loaded agents:"
          ls .opencode/agents/ 2>/dev/null || echo "  (none)"
        displayName: 'Resolve system configuration'

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          SUBMODULE_MODE="$(SUBMODULE_MODE)"
          SYSTEM="$(DETECTED_SYSTEM)"

          # Build prompt with appropriate systems-dir arguments
          if [ "$SUBMODULE_MODE" = "true" ]; then
            PROMPT=$(./$SCRIPTS/build-prompt.sh \
              --mode implement \
              --system "$SYSTEM" \
              --context workitem-context.json \
              --systems-dir systems \
              --systems-dir template/systems)
          else
            PROMPT=$(./$SCRIPTS/build-prompt.sh \
              --mode implement \
              --system "$SYSTEM" \
              --context workitem-context.json)
          fi

          # Capture agent and skills info for logging
          AGENT_NAME="implement"
          SKILLS_LIST=$(ls -1 .opencode/skills/ 2>/dev/null | sed 's/\.md$//' | tr '\n' ', ' | sed 's/,$//')
          AGENTS_LIST=$(ls -1 .opencode/agents/ 2>/dev/null | sed 's/\.md$//' | tr '\n' ', ' | sed 's/,$//')

          # Log what we're sending to OpenCode
          echo "=============================================="
          echo "OPENCODE INPUT - IMPLEMENT MODE"
          echo "=============================================="
          echo "Agent: $AGENT_NAME"
          echo "System: $SYSTEM"
          echo "Submodule Mode: $SUBMODULE_MODE"
          echo ""
          echo "--- AVAILABLE SKILLS ---"
          echo "$SKILLS_LIST"
          echo ""
          echo "--- AVAILABLE AGENTS ---"
          echo "$AGENTS_LIST"
          echo ""
          echo "--- PROMPT ---"
          echo "$PROMPT"
          echo ""
          echo "--- OPENCODE CONFIG ---"
          cat ./opencode.json
          echo ""
          echo "=============================================="

          # Create OpenCode auth directory and inject auth.json
          mkdir -p $HOME/.local/share/opencode
          echo "$OPENCODE_AUTH_JSON" > $HOME/.local/share/opencode/auth.json

          # Build docker arguments
          DOCKER_ARGS="--rm"
          DOCKER_ARGS="$DOCKER_ARGS -e ADO_MCP_AUTH_TOKEN"
          DOCKER_ARGS="$DOCKER_ARGS -e AZURE_DEVOPS_ORG_URL=https://dev.azure.com/$AZURE_DEVOPS_ORG"
          DOCKER_ARGS="$DOCKER_ARGS -v $HOME/.local/share/opencode:/root/.local/share/opencode"
          DOCKER_ARGS="$DOCKER_ARGS -v $(pwd):/workspace"
          DOCKER_ARGS="$DOCKER_ARGS -w /workspace"

          # Add CA certificates if available (for internal HTTPS endpoints)
          # Organizations can provide certs/*.crt files for internal SSL/TLS
          # Mount to /tmp/org-certs and copy to proper location in entrypoint
          CA_MOUNT=""
          if [ -d "certs" ] && ls certs/*.crt 1>/dev/null 2>&1; then
            echo "Mounting organization CA certificates..."
            CA_MOUNT="-v $(pwd)/certs:/tmp/org-certs:ro"
          fi

          # Run OpenCode with implement agent
          # If CA certs mounted, copy to proper location and run update-ca-certificates
          # Must use --entrypoint to override container's default entrypoint
          # Set NODE_EXTRA_CA_CERTS so Node.js also trusts the certs
          # Use $1 for prompt (underscore is placeholder for $0)
          if [ -n "$CA_MOUNT" ]; then
            docker run $DOCKER_ARGS $CA_MOUNT --entrypoint sh \
              ${{ parameters.dockerImage }} -c '
                cp /tmp/org-certs/*.crt /usr/local/share/ca-certificates/ 2>/dev/null
                update-ca-certificates 2>/dev/null
                export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
                opencode run --agent implement "$1"
              ' _ "$PROMPT"
          else
            docker run $DOCKER_ARGS \
              ${{ parameters.dockerImage }} run --agent implement "$PROMPT"
          fi
        displayName: 'Run OpenCode Implementation'
        env:
          OPENCODE_AUTH_JSON: $(OPENCODE_AUTH_JSON)
          ADO_MCP_AUTH_TOKEN: $(System.AccessToken)
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)

      - script: |
          SUBMODULE_MODE="$(SUBMODULE_MODE)"
          SYSTEM="$(DETECTED_SYSTEM)"

          # Find config file (local takes priority)
          if [ "$SUBMODULE_MODE" = "true" ]; then
            if [ -f "systems/$SYSTEM/config.yml" ]; then
              CONFIG_FILE="systems/$SYSTEM/config.yml"
            elif [ -f "template/systems/$SYSTEM/config.yml" ]; then
              CONFIG_FILE="template/systems/$SYSTEM/config.yml"
            elif [ -f "systems/_default/config.yml" ]; then
              CONFIG_FILE="systems/_default/config.yml"
            else
              CONFIG_FILE="template/systems/_default/config.yml"
            fi
          else
            CONFIG_FILE="systems/$SYSTEM/config.yml"
            if [ ! -f "$CONFIG_FILE" ]; then
              CONFIG_FILE="systems/_default/config.yml"
            fi
          fi

          echo "Running quality gates from: $CONFIG_FILE"

          # Extract and run build command
          BUILD_CMD=$(grep -A1 "build:" "$CONFIG_FILE" | grep "command:" | cut -d'"' -f2)
          if [ -n "$BUILD_CMD" ]; then
            echo "Running build: $BUILD_CMD"
            eval "$BUILD_CMD" || exit 1
          fi

          # Extract and run test command
          TEST_CMD=$(grep -A1 "test:" "$CONFIG_FILE" | grep "command:" | cut -d'"' -f2)
          if [ -n "$TEST_CMD" ]; then
            echo "Running tests: $TEST_CMD"
            eval "$TEST_CMD" || exit 1
          fi

          # Extract and run lint command
          LINT_CMD=$(grep -A1 "lint:" "$CONFIG_FILE" | grep "command:" | cut -d'"' -f2)
          if [ -n "$LINT_CMD" ]; then
            echo "Running lint: $LINT_CMD"
            eval "$LINT_CMD" || exit 1
          fi

          echo "All quality gates passed!"
        displayName: 'Run Definition of Done checks'
        continueOnError: false

      - script: |
          # Commit and push changes
          git add -A
          git commit -m "AI Agent: Implement work item #${{ parameters.workItemId }}

          Automated implementation by AI Agent pipeline.
          Work Item: ${{ parameters.workItemId }}"

          # Push to remote
          git push --set-upstream origin "$(BRANCH_NAME)"
        displayName: 'Commit and push changes'
        env:
          GH_HOST: $(GH_HOST)
          GH_TOKEN: $(GHE_TOKEN)

      - script: |
          # Create Pull Request using GitHub CLI
          gh pr create \
            --title "AI Agent: Work Item #${{ parameters.workItemId }}" \
            --body "## Automated PR

          This PR was created by the AI Agent pipeline.

          **Work Item:** #${{ parameters.workItemId }}
          **Pipeline:** [Build $(Build.BuildId)]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId))

          Please review the changes and merge when ready." \
            --base main \
            --head "$(BRANCH_NAME)" > pr-url.txt

          PR_URL=$(cat pr-url.txt)
          echo "##vso[task.setvariable variable=PR_URL]$PR_URL"
          echo "Created PR: $PR_URL"
        displayName: 'Create Pull Request'
        env:
          GH_HOST: $(GH_HOST)
          GH_TOKEN: $(GHE_TOKEN)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          # Update work item with PR link (upsert: update existing or create new)
          PR_URL=$(cat pr-url.txt)

          ./$SCRIPTS/update-workitem.sh \
            --work-item-id "${{ parameters.workItemId }}" \
            --upsert-comment "AI-IMPLEMENTATION" \
            --add-comment "## Implementation Complete

          Pull Request created: $PR_URL

          Please review and merge when ready.

          ---
          *Agent: implement*" \
            --remove-tag "ai-working" \
            --remove-tag "ai-approved"
        displayName: 'Update work item with PR link'
        env:
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)
          AZURE_DEVOPS_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_PAT: $(System.AccessToken)

      - script: |
          SCRIPTS="$(SCRIPTS_DIR)"
          # Notify on failure
          ./$SCRIPTS/send-teams-notification.sh \
            --type "error" \
            --work-item-id "${{ parameters.workItemId }}" \
            --message "Implementation stage failed" \
            --pipeline-url "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"

          ./$SCRIPTS/update-workitem.sh \
            --work-item-id "${{ parameters.workItemId }}" \
            --add-tag "ai-failed" \
            --remove-tag "ai-working" \
            --add-comment "## Implementation Failed

          The AI Agent encountered an error during implementation.
          Please check the [pipeline logs]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)) for details."
        displayName: 'Handle failure'
        condition: failed()
        env:
          AZURE_DEVOPS_ORG: $(AZURE_DEVOPS_ORG)
          AZURE_DEVOPS_PROJECT: $(System.TeamProject)
          AZURE_DEVOPS_PAT: $(System.AccessToken)
          TEAMS_WEBHOOK_URL: $(TEAMS_WEBHOOK_URL)
